### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by jacksparrowFF2** [rusterx/blender_chemicals#1]
![image](https://user-images.githubusercontent.com/23632933/70053132-bf6af600-160f-11ea-9f7c-f94e448f10ec.png)

安装说明文档进行安装，可是为什么会出现这个错误？
开发者可以指导一下吗？

win10 系统
python 3.7.4

**Comment by rusterx** [comment]
可能是你输入的smile格式不正确？导致opebabel无法正常解析，当然这个插件的遇到异常的提醒有点不友好。

**Comment by jacksparrowFF2** [comment]
谢谢开发者的解答，我已经解决这个问题了。

在下载这个程序之前，我尝试通过 `pip install openbabel` 去安装 openbabel，虽然提示安装成功，但实际上会出现上述这种错误。

这个错误与 blender 的版本关系不大，主要与 python 有关。

所以强烈建议使用这个程序时，确保电脑内的 python 环境是一个干净的状态，我的做法是完全卸载原有的 python 环境，然后安装 miniconda3 或者 anaconda3，并在最后一步勾选上两个选项（添加至环境变量和将 conda 中内置 python 作为解释器）。

随后，再按照开发者的说明进行安装。

另补充一个方便查询 smile 的网站：https://pubchem.ncbi.nlm.nih.gov/
（原谅我不会用开发者提供的工具）

![methane](https://user-images.githubusercontent.com/23632933/70103949-86666c00-1677-11ea-88a7-7de90569f61c.png)
